FROM node:20

# Set working directory
WORKDIR /app

# Copy only package files first (for cache optimization)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the files
COPY . .

# Build the project
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
