services:
  backend:
    image: korarak777/flask-backend:latest
    container_name: flask-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    networks:
      - app-network

  frontend:
    image: korarak777/nuxt-frontend:latest
    container_name: nuxt-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
